# Generated by Django 4.1.7 on 2026-04-01 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0009_interviewscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewscore',
            name='round',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('HR', 'HR'), ('TECH', 'Technical')], default='BASIC', max_length=10),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='communication',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='emotion',
            field=models.CharField(default='Neutral', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='grade',
            field=models.CharField(default='F', max_length=5),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='responses/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='responses/video/')),
                ('round', models.CharField(choices=[('BASIC', 'Basic'), ('HR', 'HR'), ('TECH', 'Technical')], default='BASIC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
